[project]
name = "wasm-semantics"
version = "1.0.0"
source = "."

[targets.llvm]
main-file = 'test.md'
main-module = 'WASM-TEST'
backend='llvm'

[targets.haskell]
main-file = 'kwasm-lemmas.md'
backend='haskell'
